export const Language = [
  {id: 1, language: 'Hindi'},
  {id: 2, language: 'English'},
  {id: 3, language: 'Spanish'},
  {id: 4, language: 'Chinese (Mandarin)'},
  {id: 5, language: 'Arabic'},
  {id: 6, language: 'French'},
  {id: 7, language: 'Russian'},
  {id: 8, language: 'Japanese'},
  {id: 9, language: 'German'},
  {id: 10, language: 'Portuguese'},
  {id: 11, language: 'Bengali'},
  {id: 12, language: 'Punjabi'},
  {id: 13, language: 'Urdu'},
  {id: 14, language: 'Italian'},
  {id: 15, language: 'Dutch'},
  {id: 16, language: 'Korean'},
  {id: 17, language: 'Turkish'},
  {id: 18, language: 'Vietnamese'},
  {id: 19, language: 'Swedish'},
  {id: 20, language: 'Finnish'},
  {id: 21, language: 'Greek'},
  {id: 22, language: 'Polish'},
  {id: 23, language: 'Thai'},
  {id: 24, language: 'Hebrew'},
];
