export const Skill = [
  {id: 1, skill: 'Nadi'},
  {id: 2, skill: 'Vedic'},
  {id: 3, skill: 'Numerology'},
  {id: 4, skill: 'Vastu'},
  {id: 5, skill: 'Prashana'},
  {id: 6, skill: 'KP'},
  {id: 7, skill: 'Lal Kitab'},
  {id: 8, skill: 'Western'},
  {id: 9, skill: 'Tarot'},
  {id: 10, skill: 'Palmistry'},
  {id: 11, skill: 'Horary'},
  {id: 12, skill: 'Face Reading'},
  {id: 13, skill: 'Psychic'},
  {id: 14, skill: 'Life Coach'},
  {id: 15, skill: 'Cartomancy'},
  {id: 16, skill: 'Loshu Grid'},
  {id: 17, skill: 'Psychologist'},
];
